### ISSUE TITLE
Issue with setting up simple project with this package.

### ISSUE THREAD

**Issue by oliverfindl** [mbadal/psr15-symfony-bundle#1]
Hello,

I'm having issue with setting up yours package according to [docs](https://profesia.github.io/psr15-symfony-bundle/), which seems to be out-of-sync with this repo (`psr15` vs `profesia_psr15`, missing default config after installation, ...).

I'm trying to setup simple [symfony/skeleton](https://github.com/symfony/skeleton) project with only [symfony/twig-pack](https://github.com/symfony/twig-pack), [middlewares/response-time](https://github.com/middlewares/response-time) and yours package. I'm newbie to Symfony, but I got this far:

```yaml
# services.yaml

services:

    # ...

    App\Middleware\ResponseTimeAlias:
        class: Middlewares\ResponseTime
        # arguments:
            # $serverRequestFactory: '@nyholm.psr7.psr17_factory'
            # $responseFactory: '@nyholm.psr7.psr17_factory'
```

```yaml
# profesia_psr15.yaml

profesia_psr15:
    use_cache: false
    middleware_chains:
        ResponseTimeMiddlewareChain:
            - App\Middleware\ResponseTimeAlias

    routing:
        HomepageRoute:
            middleware_chain: ResponseTimeMiddlewareChain
            conditions:
                - {route_name: 'homepage'}
```

Which dies with TypeError:
```
Profesia\Symfony\Psr15Bundle\Resolver\Strategy\RouteNameResolver::registerRouteMiddleware(): Argument #2 ($middlewareChain) must be of type Delvesoft\Psr15\Middleware\AbstractMiddlewareChainItem, Middlewares\ResponseTime given, called in <PATH_TO_PROJECT>/var/cache/dev/Container4vRTNvh/App_KernelDevDebugContainer.php on line 800
```

Can you please point me out, where I made mistake? Or its a bug caused by only 1 middleware in chain?

Thanks.
